version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: cubeearth/ldap-server
    ports:
      - 3389:389
    volumes:
      - ./ldif:/ldif
