apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-server
  labels:
    app: ldap-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap-server
  template:
    metadata:
      annotations:
        ssl-cert.server  : "server:ldap"
        pwd.shared: "ldap-root"
      labels:
        app: ldap-server
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
        beta.kubernetes.io/arch: amd64
      containers:
      - name: ldap-server
        image: cubeearth/ldap-server:latest
        ports:
        - containerPort: 389
        - containerPort: 636
        
---   
apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  selector:
    app: ldap-server
  ports:
  - name: http
    port: 389
  - name: https
    port: 636

